localhost_development:
  backend:
    name: file-system
    api_root: /api

backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

display_url: http://localhost:8000
media_folder: static/img
public_folder: /img

collections:
  - name: pages
    label: Pages
    description: List of pages
    folder: content/pages
    extension: mdx
    format: frontmatter
    widget: mdx
    create: true
    fields:
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "mdx-example" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Featured Image", name: "featuredimage", widget: image, required: false }
      - { label: "Body", name: "body", widget: "mdx" }
      - { label: "Category", name: "category", widget: "category", required: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }

  - name: articles
    label: Articles
    description: List of articles
    folder: content/articles
    extension: mdx
    format: frontmatter
    widget: mdx
    create: true
    fields:
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "mdx-example" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Featured Image", name: "featuredimage", widget: image, required: false }
      - { label: "Body", name: "body", widget: "mdx" }
      - { label: "Category", name: "category", widget: "category", required: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }
